### ISSUE TITLE
Testing with newer versions of Julia

### ISSUE THREAD

**Issue by joseraulgonzalez** [justindressel/QuantumBayesian.jl#7]
The following lists some changes from v0.6 onwards that affect QuantumBayesian.jl: https://github.com/JuliaLang/julia/blob/v0.6.0/NEWS.md

In particular, note the following changes
* immutable -> struct
* type -> mutable struct
* abstract -> abstract type
* typealias -> const ALIAS = ORIG

These changes cause a laundry list of warnings in the CI testing, as well as an error related to subtyping.

To move forward, maybe Compat.jl can be added to the list of requirements of the package and code for different version targets can be stored in different branches of the repo.

Thoughts?

**Comment by justindressel** [comment]
Agreed. Including Compat.jl is a good idea going forward. Let's get a patch ready to handle v0.6 soon.

**Comment by joseraulgonzalez** [comment]
I see that compatibility with v0.6 has been fixed. Thank you!

**Comment by justindressel** [comment]
No problem. Note that I looked into using Compat for backwards compatibility, but dropped it due to issues with changing how inner constructors behaved.
